### ISSUE TITLE
Error using

### ISSUE THREAD

**Issue by CEPHAS-01** [marbl/ModDotPlot#2]
Hi Alex,

I installed the tool and when I tried to run it, I encountered the error shown:

 
Traceback (most recent call last):
  File "/home/Tools/software/venv/bin/moddotplot", line 33, in <module>
    sys.exit(load_entry_point('moddotplot==0.3.0', 'console_scripts', 'moddotplot')())
  File "/home/Tools/software/venv/bin/moddotplot", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/mambaforge/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/mambaforge/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/Tools/software/ModDotPlot/moddotplot/__main__.py", line 4, in <module>
    from moddotplot.moddotplot import main
  File "/home/Tools/software/ModDotPlot/moddotplot/moddotplot.py", line 4, in <module>
    from moddotplot.interactive import run_dash
  File "/home/Tools/software/ModDotPlot/moddotplot/interactive.py", line 2, in <module>
    from moddotplot.estimate_identity import (
ImportError: cannot import name 'poisson_distance' from 'moddotplot.estimate_identity' (/home/Tools/software/ModDotPlot/moddotplot/estimate_identity.py)

Please kindly help me look into this.

Thank you.

**Comment by alexsweeten** [comment]
Hi Temitayo,

This error was due to a function not being included. I've added the function as of 20d2c85c0703ad5160ff3d94f5821f90f354df53 . 

I'm pushing a lot of changes this week, so bear with me as there will likely be some more bugs as we add on some more features to Mod.Plot. Let me know if you run into any more problems. Thanks!

**Comment by CEPHAS-01** [comment]
Hello Alex,

Thank you so much for the prompt feedback.
After using the commit you specified the following error came up:

Traceback (most recent call last):
  File "/home/mambaforge/bin/moddotplot", line 33, in <module>
    sys.exit(load_entry_point('moddotplot==0.4.0', 'console_scripts', 'moddotplot')())
  File "/home/mambaforge/bin/moddotplot", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/mambaforge/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/mambaforge/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/Tools/software/ModDotPlot/moddotplot/__main__.py", line 4, in <module>
    from moddotplot.moddotplot import main
  File "/home/Tools/software/ModDotPlot/moddotplot/moddotplot.py", line 4, in <module>
    from moddotplot.interactive import run_dash
  File "/home/Tools/software/ModDotPlot/moddotplot/interactive.py", line 14, in <module>
    import dash_daq as daq
ModuleNotFoundError: No module named 'dash_daq'

I guess this is still due to the changes still being effected.
Perhaps I'll wait until the changes are completed and the repo is stable.

Thanks.

**Comment by alexsweeten** [comment]
`ModuleNotFoundError: No module named 'dash_daq'` should be fixed by running:

`pip install dash_daq`

**Comment by CEPHAS-01** [comment]
Hi Alex,

This works fine now.
Thanks!

**Comment by alexsweeten** [comment]
Great to hear!

I'll keep this issue up for a little while. Please let me know if you run into any more bugs or issues.

**Comment by CEPHAS-01** [comment]
Hi Alex,
It's really been cool using this tool, easy to use and very interactive.

Does it handle a sequence spanning more than one contig?
I just produced the view of a chromosome spanning 3 contigs, but I see only the first one on the plot.

Thanks

**Comment by alexsweeten** [comment]
Apologies for overseeing your latest question. Yes, ModDotPlot will run on every contig found in each fasta file provided as input.

Closing this issue now to clean up backlog.
